In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
pip install XGBClassifier

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement XGBClassifier
ERROR: No matching distribution found for XGBClassifier

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, plot_confusion_matrix
from sklearn.model_selection import GridSearchCV
from  xgboost import XGBClassifier
from sklearn import metrics
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [4]:
data = pd.read_csv('C:/Users/User/Desktop/gender (1).csv')

In [5]:
shape_data = data.shape
data_describe = data.describe().T
data_numeric=data._get_numeric_data()
data_null = data_numeric.isnull().sum()/len(data) * 100
data_describe['Missing %']=data_null
print('Количество строк, столбцов:', shape_data)
print('Обзор данных', '\n')
display(data.sample(10))
print('Информация о датасете', '\n')
display(data.info())
print('Cтатистика', '\n')
display(data_describe)

Количество строк, столбцов: (2515, 23)
Обзор данных

,Unnamed: 0,index,long_hair,forehead_width_cm,forehead_height_cm,forehead_width_mm,forehead_width_conventional_units,nose_wide,nose_long,lips_thin,...,long_hair.1,forehead_width_cm.1,forehead_height_cm.1,forehead_width_mm.1,forehead_width_conventional_units.1,nose_wide.1,nose_long.1,lips_thin.1,distance_nose_to_lip_long.1,gender.1
688,688,688,0.702717,12.2,6.4,122.0,0.051613,0.480238,0.873222,0.451261,...,0.848269,12.6,5.4,126.0,0.077419,0.793958,0.741032,0.740636,0.969414,Male
1153,1153,1153,0.919113,13.0,6.0,130.0,0.103226,0.305978,0.493411,0.389105,...,0.856249,13.3,6.1,133.0,0.122581,0.576034,0.886995,0.954837,0.912138,Male
1853,1853,1853,0.511599,14.5,5.4,145.0,0.200000,0.529473,0.961197,0.021838,...,0.581574,14.9,5.5,149.0,0.225806,0.804514,0.697659,0.600395,0.747034,Male
1851,1851,1851,0.379393,13.6,5.4,136.0,0.141935,0.307522,0.101448,0.475579,...,0.656354,13.0,5.5,130.0,0.103226,0.073012,0.413293,0.045028,0.186356,Female
1996,1996,1996,0.995015,12.8,5.7,128.0,0.090323,0.092522,0.450773,0.453760,...,0.893942,12.3,6.3,123.0,0.058065,0.085869,0.873461,0.070200,0.358386,Female
30,30,30,0.944804,15.3,5.2,153.0,0.251613,0.571456,0.751429,0.803025,...,0.741973,15.3,6.7,153.0,0.251613,0.765379,0.989876,0.550079,0.423970,Male
1668,1668,1668,0.515873,13.4,6.5,134.0,0.129032,0.926052,0.267297,0.972849,...,0.933948,12.3,6.5,123.0,0.058065,0.447728,0.089440,0.428387,0.996814,Female
941,941,941,0.846821,12.2,5.7,122.0,0.051613,0.653348,0.827443,0.373273,...,0.690914,12.5,5.9,125.0,0.070968,0.089858,0.380384,0.431288,0.174619,Female
2297,2297,2297,0.836889,12.3,5.1,123.0,0.058065,0.153178,0.292298,0.169494,...,0.657158,14.8,5.7,148.0,0.219355,0.890066,0.770852,0.623897,0.659114,Male
22,22,22,0.685205,12.9,6.4,129.0,0.096774,0.848272,0.122876,0.003801,...,0.814588,13.5,5.8,135.0,0.135484,0.171445,0.113482,0.217987,0.178364,Female

Информация о датасете

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2515 entries, 0 to 2514
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Unnamed: 0                           2515 non-null   int64
 1   index                                2515 non-null   int64
 2   long_hair                            2515 non-null   float64
 3   forehead_width_cm                    2515 non-null   float64
 4   forehead_height_cm                   2515 non-null   float64
 5   forehead_width_mm                    2515 non-null   float64
 6   forehead_width_conventional_units    2515 non-null   float64
 7   nose_wide                            2515 non-null   float64
 8   nose_long                            2515 non-null   float64
 9   lips_thin                            2515 non-null   float64
 10  distance_nose_to_lip_long            2515 non-null   float64
 11  gender                               1514 non-null   object
 12  index.1                              2515 non-null   int64
 13  long_hair.1                          2486 non-null   float64
 14  forehead_width_cm.1                  2486 non-null   float64
 15  forehead_height_cm.1                 2486 non-null   float64
 16  forehead_width_mm.1                  2486 non-null   float64
 17  forehead_width_conventional_units.1  2486 non-null   float64
 18  nose_wide.1                          2486 non-null   float64
 19  nose_long.1                          2486 non-null   float64
 20  lips_thin.1                          2486 non-null   float64
 21  distance_nose_to_lip_long.1          2486 non-null   float64
 22  gender.1                             2486 non-null   object
dtypes: float64(18), int64(3), object(2)
memory usage: 452.0+ KB

None

Cтатистика

,count,mean,std,min,25%,50%,75%,max,Missing %
Unnamed: 0,2515.0,1257.000000,726.162287,0.000000,628.500000,1257.000000,1885.500000,2514.000000,0.000000
index,2515.0,1257.000000,726.162287,0.000000,628.500000,1257.000000,1885.500000,2514.000000,0.000000
long_hair,2515.0,0.681951,0.223119,0.000353,0.563491,0.706560,0.856213,0.999820,0.000000
forehead_width_cm,2515.0,13.191451,1.105286,11.400000,12.200000,13.200000,14.000000,15.500000,0.000000
forehead_height_cm,2515.0,5.956024,0.543112,5.100000,5.500000,5.900000,6.400000,7.100000,0.000000
forehead_width_mm,2515.0,131.914513,11.052860,114.000000,122.000000,132.000000,140.000000,155.000000,0.000000
forehead_width_conventional_units,2515.0,0.115578,0.071309,0.000000,0.051613,0.116129,0.167742,0.264516,0.000000
nose_wide,2515.0,0.498657,0.286892,0.000030,0.249588,0.504837,0.739788,0.999192,0.000000
nose_long,2515.0,0.505979,0.283629,0.000038,0.259361,0.515154,0.749930,0.999722,0.000000
lips_thin,2515.0,0.502013,0.286526,0.000474,0.255767,0.509687,0.755422,0.999950,0.000000
distance_nose_to_lip_long,2515.0,0.501994,0.290545,0.000472,0.254755,0.504384,0.745948,0.999846,0.000000
index.1,2515.0,3714.334394,817.968037,0.000000,3114.500000,3743.000000,4371.500000,5000.000000,0.000000
long_hair.1,2486.0,0.687183,0.221110,0.005634,0.571801,0.711019,0.862535,0.999977,1.153082
forehead_width_cm.1,2486.0,13.171400,1.109120,11.400000,12.200000,13.100000,14.000000,15.500000,1.153082
forehead_height_cm.1,2486.0,5.936484,0.539327,5.100000,5.500000,5.900000,6.300000,7.100000,1.153082
forehead_width_mm.1,2486.0,131.713998,11.091201,114.000000,122.000000,131.000000,140.000000,155.000000,1.153082
forehead_width_conventional_units.1,2486.0,0.114284,0.071556,0.000000,0.051613,0.109677,0.167742,0.264516,1.153082
nose_wide.1,2486.0,0.492083,0.287022,0.000732,0.245063,0.481694,0.743941,0.999825,1.153082
nose_long.1,2486.0,0.503464,0.287333,0.000936,0.257632,0.499969,0.752445,0.999892,1.153082
lips_thin.1,2486.0,0.493168,0.285306,0.000156,0.259642,0.478671,0.738107,0.999677,1.153082
distance_nose_to_lip_long.1,2486.0,0.494092,0.284510,0.000160,0.248990,0.489269,0.740587,0.999834,1.153082

In [6]:
data.isnull().sum()

Unnamed: 0                                0
index                                     0
long_hair                                 0
forehead_width_cm                         0
forehead_height_cm                        0
forehead_width_mm                         0
forehead_width_conventional_units         0
nose_wide                                 0
nose_long                                 0
lips_thin                                 0
distance_nose_to_lip_long                 0
gender                                 1001
index.1                                   0
long_hair.1                              29
forehead_width_cm.1                      29
forehead_height_cm.1                     29
forehead_width_mm.1                      29
forehead_width_conventional_units.1      29
nose_wide.1                              29
nose_long.1                              29
lips_thin.1                              29
distance_nose_to_lip_long.1              29
gender.1                                 29
dtype: int64

In [7]:
col_names = []
for col in data.columns:
    col_names.append(col)

In [8]:
data_1 = data[col_names[1:12]]

In [9]:
data_2 = data[col_names[12:]].rename(columns={col_names[12]: col_names[1], 
                                   col_names[13]: col_names[2],
                                  col_names[14]: col_names[3],
                                  col_names[15]: col_names[4],
                                  col_names[16]: col_names[5],
                                  col_names[17]: col_names[6],
                                  col_names[18]: col_names[7],
                                  col_names[19]: col_names[8],
                                  col_names[20]: col_names[9],
                                  col_names[21]: col_names[10],
                                  col_names[22]: col_names[11]}, errors="raise")

In [10]:
frames=[data_1, data_2]

final = pd.concat(frames)
final

,index,long_hair,forehead_width_cm,forehead_height_cm,forehead_width_mm,forehead_width_conventional_units,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,0,0.704275,11.8,6.1,118.0,0.025806,0.895614,0.477485,0.841261,0.902628,NaN
1,1,0.118690,14.0,5.4,140.0,0.167742,0.202520,0.186825,0.719697,0.309122,NaN
2,2,0.203894,11.8,6.3,118.0,0.025806,0.892793,0.723152,0.725821,0.720640,NaN
3,3,0.386228,14.4,6.1,144.0,0.193548,0.024963,0.562005,0.831515,0.770379,NaN
4,4,0.564020,13.5,5.9,135.0,0.135484,0.415389,0.063705,0.211584,0.157217,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2510,4996,0.645930,13.6,5.1,136.0,0.141935,0.443641,0.255464,0.116379,0.042459,Female
2511,4997,0.501251,11.9,5.4,119.0,0.032258,0.473038,0.469482,0.067636,0.210801,Female
2512,4998,0.701357,12.9,5.7,129.0,0.096774,0.388300,0.428321,0.322559,0.199743,Female
2513,4999,0.684078,13.2,6.2,132.0,0.116129,0.067981,0.167563,0.218222,0.370723,Female
2514,5000,0.794726,15.4,5.4,154.0,0.258065,0.812078,0.956397,0.692107,0.531950,Male

In [11]:
final[['nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair']] = final[['nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair']].round()
final

,index,long_hair,forehead_width_cm,forehead_height_cm,forehead_width_mm,forehead_width_conventional_units,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,0,1.0,11.8,6.1,118.0,0.025806,1.0,0.0,1.0,1.0,NaN
1,1,0.0,14.0,5.4,140.0,0.167742,0.0,0.0,1.0,0.0,NaN
2,2,0.0,11.8,6.3,118.0,0.025806,1.0,1.0,1.0,1.0,NaN
3,3,0.0,14.4,6.1,144.0,0.193548,0.0,1.0,1.0,1.0,NaN
4,4,1.0,13.5,5.9,135.0,0.135484,0.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2510,4996,1.0,13.6,5.1,136.0,0.141935,0.0,0.0,0.0,0.0,Female
2511,4997,1.0,11.9,5.4,119.0,0.032258,0.0,0.0,0.0,0.0,Female
2512,4998,1.0,12.9,5.7,129.0,0.096774,0.0,0.0,0.0,0.0,Female
2513,4999,1.0,13.2,6.2,132.0,0.116129,0.0,0.0,0.0,0.0,Female
2514,5000,1.0,15.4,5.4,154.0,0.258065,1.0,1.0,1.0,1.0,Male

In [12]:
final['gender'].value_counts()

Female    2006
Male      1994
Name: gender, dtype: int64

In [13]:
final.isnull().sum()

index                                   0
long_hair                              29
forehead_width_cm                      29
forehead_height_cm                     29
forehead_width_mm                      29
forehead_width_conventional_units      29
nose_wide                              29
nose_long                              29
lips_thin                              29
distance_nose_to_lip_long              29
gender                               1030
dtype: int64

In [14]:
final = final[final['long_hair'].notnull()]

In [15]:
final.isnull().sum()

index                                   0
long_hair                               0
forehead_width_cm                       0
forehead_height_cm                      0
forehead_width_mm                       0
forehead_width_conventional_units       0
nose_wide                               0
nose_long                               0
lips_thin                               0
distance_nose_to_lip_long               0
gender                               1001
dtype: int64

In [16]:
pred_x = final[:1001].drop(columns = 'gender')
pred_x

,index,long_hair,forehead_width_cm,forehead_height_cm,forehead_width_mm,forehead_width_conventional_units,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long
0,0,1.0,11.8,6.1,118.0,0.025806,1.0,0.0,1.0,1.0
1,1,0.0,14.0,5.4,140.0,0.167742,0.0,0.0,1.0,0.0
2,2,0.0,11.8,6.3,118.0,0.025806,1.0,1.0,1.0,1.0
3,3,0.0,14.4,6.1,144.0,0.193548,0.0,1.0,1.0,1.0
4,4,1.0,13.5,5.9,135.0,0.135484,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
996,996,0.0,12.7,6.0,127.0,0.083871,0.0,0.0,0.0,1.0
997,997,1.0,14.1,5.3,141.0,0.174194,0.0,0.0,0.0,0.0
998,998,1.0,12.1,6.2,121.0,0.045161,1.0,1.0,1.0,0.0
999,999,1.0,14.9,6.0,149.0,0.225806,1.0,1.0,1.0,1.0
1000,1000,1.0,14.2,5.7,142.0,0.180645,1.0,1.0,1.0,1.0

In [17]:
x = final[1001:].drop(columns = 'gender')
y = final[1001:]['gender'].replace({"Female":1,"Male":0})

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=42)

In [19]:
model = KNeighborsClassifier()
k_range = list(range(1, 100))
param_grid = dict(n_neighbors=k_range)
  
grid = GridSearchCV(model, param_grid, cv=10, scoring='accuracy', return_train_score=False,verbose=1)
  
grid_search=grid.fit(x_train, y_train)

Fitting 10 folds for each of 99 candidates, totalling 990 fits

In [20]:
print(grid_search.best_params_)

{'n_neighbors': 1}

In [21]:
accuracy = grid_search.best_score_ *100
print("Accuracy for our training dataset with tuning is : {:.2f}%".format(accuracy) )

Accuracy for our training dataset with tuning is : 59.54%

In [22]:
model = XGBClassifier(learning_rate=0.01).fit(x_train, y_train)
y_pred = model.predict(x_test)

[22:08:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [23]:
pr, rc, fs, sup = metrics.precision_recall_fscore_support(y_test, y_pred, average='macro')
res = {"Accuracy": round(metrics.accuracy_score(y_test, y_pred), 4),
                              "Precision": round(pr, 4), "Recall":round(rc, 4), "FScore":round(fs, 4)}
res

{'Accuracy': 0.9756, 'Precision': 0.9756, 'Recall': 0.9757, 'FScore': 0.9756}

In [24]:
pred_y = model.predict(pred_x)
res = pd.DataFrame(pred_y, columns = ['gender']).replace({1: "Female",0 : "Male"})
res.to_csv('C:/Users/User/Desktop/result.csv',index=False)

In [25]:
res

      gender
0       Male
1     Female
2       Male
3       Male
4     Female
...      ...
996   Female
997   Female
998     Male
999     Male
1000    Male

[1001 rows x 1 columns]